CREATE DATABASE timerbot DEFAULT CHARSET=utf8mb4;

CREATE TABLE user (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  display_name VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  mid VARCHAR(60) NOT NULL,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  UNIQUE(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE timer (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(256) NOT NULL,
  mid VARCHAR(60) NOT NULL,
  alert_at INT NOT NULL,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  INDEX(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE work (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(256) NOT NULL,
  mid VARCHAR(60) NOT NULL,
  active_time INT NOT NULL,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  INDEX(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
