;;CREATE DATABASE timerbot DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  display_name VARCHAR(256) NOT NULL DEFAULT '',
  name VARCHAR(256) NOT NULL DEFAULT '',
  mid VARCHAR(60) NOT NULL,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  UNIQUE(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE timers (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(256) NOT NULL DEFAULT '',
  mid VARCHAR(60) NOT NULL DEFAULT '',
  alert_at INT NOT NULL DEFAULT 0,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  INDEX(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE works (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(256) NOT NULL DEFAULT '',
  mid VARCHAR(60) NOT NULL DEFAULT '',
  active_time INT NOT NULL DEFAULT 0,
  created_at INT NOT NULL DEFAULT 0,
  updated_at INT NOT NULL DEFAULT 0,
  INDEX(mid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
